const ENV = {
    API_URL: window.APP_CONFIG?.API_URL || process.env.MIX_HOST,
    API_KEY: window.APP_CONFIG?.API_KEY || process.env.MIX_API_KEY,
    GOOGLE_MAP_KEY: window.APP_CONFIG?.GOOGLE_MAP_KEY || process.env.MIX_GOOGLE_MAP_KEY,
    DEMO: window.APP_CONFIG?.DEMO || process.env.MIX_DEMO,
    PUSHER_APP_KEY: window.APP_CONFIG?.PUSHER_APP_KEY || process.env.MIX_PUSHER_APP_KEY,
    PUSHER_APP_CLUSTER: window.APP_CONFIG?.PUSHER_APP_CLUSTER || process.env.MIX_PUSHER_APP_CLUSTER,
    PUSHER_HOST: window.APP_CONFIG?.PUSHER_HOST || process.env.MIX_PUSHER_HOST,
    PUSHER_PORT: window.APP_CONFIG?.PUSHER_PORT || process.env.MIX_PUSHER_PORT,
    PUSHER_SCHEME: window.APP_CONFIG?.PUSHER_SCHEME || process.env.MIX_PUSHER_SCHEME,
    BANK_NUMBER: window.APP_CONFIG?.BANK_NUMBER || process.env.MIX_BANK_NUMBER,
    BANK_NAME: window.APP_CONFIG?.BANK_NAME || process.env.MIX_BANK_NAME,
    BANK_PREFIX: window.APP_CONFIG?.BANK_PREFIX || process.env.MIX_BANK_PREFIX,
    CASHCARD_PREFIX: window.APP_CONFIG?.CASHCARD_PREFIX || process.env.MIX_CASHCARD_PREFIX,
    BANK_CONTENT: window.APP_CONFIG?.BANK_CONTENT || process.env.MIX_BANK_CONTENT,
};
export default ENV;
